### ISSUE TITLE
Claims on speed (benchmarking)

### ISSUE THREAD

**Issue by BradKML** [dlom/anydice#3]
Comparing this repo and https://github.com/LordSembor/DnDice https://github.com/curso-r/droll and see which one is faster

**Comment by dlom** [comment]
Please note that the `anydice` package simply makes an API call to https://anydice.com/.  Any perceived latency is a direct result of this HTTP request.

**Comment by BradKML** [comment]
AN online API call rather than an offline API call?

**Comment by dlom** [comment]
That is correct
